apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: champi
  namespace: applications
spec:
  rules:
  - host: champi.tykus.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: champi
            port:
              number: 80
