apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: e2e-test-app
  namespace: default
spec:
  rules:
  - host: e2e-test-app.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: e2e-test-app
            port:
              number: 80
